file_loc : '../data/esdc_raw.xlsx'
x_col : ['fluid','field_name','operator','project_status','project_level','inplace','depth','temp','poro','perm','saturate','api_dens','visc','cap_cost','opr_cost','total_cost','avg_fluid_rate','location','region','NPV','PI']
y_col : 'prospect_rank'
out_path : "../output/"
test_size : 0.2